name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

env:
  NODE_OPTIONS: --max-old-space-size=8192 # Allocate more memory to Node.js

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Use LTS version for stability
          cache: 'yarn'

      # Step 3: Clear Yarn Cache
      - name: Clear Yarn Cache
        run: yarn cache clean

      # Step 4: Rebuild Node Modules
      - name: Remove and Reinstall Node Modules
        run: |
          rm -rf node_modules
          yarn install --frozen-lockfile
        env:
          NX_VERBOSE_LOGGING: true

      # Step 5: Build admin-dashboard
      - name: Build admin-dashboard
        run: yarn nx build admin-dashboard --prod

      # Step 6: Build client-dashboard
      - name: Build client-dashboard
        run: yarn nx build client-dashboard --prod

      # Step 7: Deploy admin-dashboard
      - name: Deploy admin-dashboard
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/apps/admin-dashboard

      # Step 8: Deploy client-dashboard
      - name: Deploy client-dashboard
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/apps/client-dashboard
